services:
  frontend:
    build: ..
    expose:
      - "3000"
    volumes:
      - ..:/app
    restart: always
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/babywalk.ru:/etc/nginx/ssl:ro
      - ~/dhparam:/etc/nginx/dhparam:ro
    depends_on:
      - frontend
    restart: always
