services:
  frontend:
    build: ..
    expose:
      - "3000"
    volumes:
      - ../node_modules:/app/node_modules
      - ../public:/app/public
      - ../package.json:/app/package.json
      - ~/front/.next:/app/.next
    restart: always
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/html:/var/www/html:ro
      - /etc/letsencrypt/live/babywalk.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/babywalk.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./sites-available:/etc/nginx/sites-available
      - ~/dhparam:/etc/nginx/dhparam:ro
      - ~/static:/static
    depends_on:
      - frontend
    restart: always
  yandex-kassa:
    build: ../../yookassa-service
    env_file:
      - .env
    expose:
      - "5000"
    volumes:
      - ~/logs:/logs
    restart: always