user www-data;

worker_processes auto;

worker_rlimit_nofile 100000;

error_log logs/error.log;

events {
    worker_connections 1024;
    # Default is 1024, or 1024 x CPU Core/s.
}

http {
    include /etc/nginx/mime.types;
    include /etc/nginx/sites-enabled/*;
    default_type application/octet-stream;

    ##
    # SSL Settings
    ##
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ecdh_curve X25519:prime256v1:secp384r1;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;

    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions

    ssl_dhparam "/etc/nginx/dhparam/dhparam.pem";

    ssl_early_data on;

    ##
    # SSL Settings - end
    ##

    access_log off;
    # Default is on, useful in test environment, but disable it to boost I/O on storage.

    sendfile on;

    tcp_nopush on;
    # Send headers in one piece, it is better than sending them one by one.

    tcp_nodelay on;
    # Don't buffer data sent, good for small data bursts in real time.

    keepalive_timeout 120;
    keepalive_requests 10000;

    gzip on;
    gzip_min_length 10240;
    gzip_comp_level 1;
    gzip_vary on;
    gzip_types text/css application/javascript;

    include /etc/nginx/conf.d/*.conf;
}
